{"name": "Попытка залогина с неправильным паролем возвращает код 404", "status": "passed", "steps": [{"name": "Получаем пару логин-пароль существующего курьера", "status": "passed", "parameters": [{"name": "exclude_login", "value": "False"}, {"name": "exclude_password", "value": "False"}, {"name": "corrupt_password", "value": "True"}], "start": 1704987299963, "stop": 1704987299963}, {"name": "Залогин курьера [POST]", "status": "passed", "parameters": [{"name": "credentials", "value": "{'login': 'login-test-777', 'password': 'corrupt-password'}"}], "start": 1704987299963, "stop": 1704987300201}, {"name": "Проверяем код ответа сервера", "status": "passed", "parameters": [{"name": "response", "value": "<Response [404]>"}, {"name": "code", "value": "404"}], "start": 1704987300201, "stop": 1704987300202}], "start": 1704987299962, "stop": 1704987300202, "uuid": "174cbd61-a7d8-42a0-b93d-3d07e9581b56", "historyId": "c4c8c460f4db6cc856ccd4b2cf04d1f7", "testCaseId": "58ba237345e49f5afa31c5e88fb02544", "fullName": "tests.test_login_courier.TestLoginCourier#test_auth_wrong_password_returns_error_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "i111355119"}, {"name": "thread", "value": "60430-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}